algoritmo "semnome"
// Função :
// Autor :
// Data : 13/03/2017
// Seção de Declarações 
var
   idade: inteiro
inicio
// Seção de Comandos 
escreva("Digite sua idade:")
leia(idade)
se idade >= 18 entao
   escreval("Maior de 18 anos. Pode assistir ao filme!")
senao
   escreval("Menor de idade. Abrir Disney Channel!")
fimse

se idade < 21 entao
   escreval("Menor de 21 anos. Não pode casar.")
senao
   escreval("Já pode casar, mas não faça isto!")
fimse


fimalgoritmo
